[package]
name = "fuzz"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"


[dependencies]
sodiumoxide = "0.2"
num_cpus = "1"
hex = "0.4"

[dependencies.crypto]
path = "../"
version = "0.2"

[profile.dev]
overflow-checks = true
panic = "abort"

[profile.release]
overflow-checks = true
panic = "abort"

[profile.bench]
overflow-checks = true

[workspace]