// A simple crate to encrypt and decrypt data into snapshot files using sodiumoxide (libsodium).
// uses the secret stream chacha20poly1305 symmetric encryption algorithm as its main encryption method.
// Snapshot file format contains a signature -> sha256 hashed-salt -> header -> data.
// Data can be encrypted prior to being put into the snapshot from the system to further secure the snapshot.
// The snapshot is sealed with a single password which is used to generate a key.  A salt is also generated by NACL
// and the key and salt are used to create the header and a push stream to encrypt the data.

mod error;
mod files;
mod logic;
mod serialize;

pub use error::{Error, Result};

pub use {
    files::{home_dir, snapshot_dir},
    logic::{decrypt_snapshot, encrypt_snapshot, update_snapshot},
    serialize::{deserialize_buffer, serialize_map},
};
