[package]
name = "snapshot"
version = "0.3.1"
authors = [
  "IOTA Stiftung",
  "tensor-programming <tensordeveloper@gmail.com>"
]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
thiserror = "1.0"
dirs-next = "2.0"
hex = "0.4.2"

  [dependencies.digest]
  version = "0.9.0"
  optional = true
  default-features = false

  [dependencies.iota-crypto]
  version = "0.5.0"
  features = [ "random", "chacha", "hmac", "sha", "x25519", "blake2b" ]

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.8.3"
proptest = "1.0.0"
criterion = "0.3.3"

  [dev-dependencies.stronghold-utils]
  path = "../../utils/utils"
  version = "0.2"

[[bench]]
name = "benchmark"
harness = false
