[package]
name = "snapshot"
version = "0.2.0"
authors = [ "tensor-programming <tensordeveloper@gmail.com>" ]
edition = "2018"
readme = "README.md"

[dependencies]
thiserror = "1.0"
dirs-next = "2.0"
hex = "0.4.2"

[dependencies.digest]
version = "0.9.0"
optional = true
default-features = false

[dependencies.iota-crypto]
git = "https://github.com/iotaledger/crypto.rs"
rev = "09ff1a94d6a87838589ccf1b874cfa3283a00f26"
features = [ "random", "chacha", "hmac", "sha", "x25519", "blake2b" ]
version = "*"
# Note: We are only adding a version so that we can publish to crates.io

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.8.3"

proptest = "0.10.1"
criterion = "0.3.3"

[dev-dependencies.stronghold-utils]
path = "../../utils"
version = "0.1"

[[bench]]
name = "benchmark"
harness = false




