[package]
name = "snapshot"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# file system
dirs-next = "2.0"

hex = "0.4.2"

[dependencies.iota-crypto]
git = "https://github.com/iotaledger/crypto.rs"
rev = "bc35d38561efcf20a50aeb0f0b08028b4b4fda46"

# TODO: remove hmac and sha when a proper kdf is chosen
features = [ "random", "chacha", "hmac", "sha" ]

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.7.3"
