[package]
name = "store"
version = "0.2.0"
authors = [ "IOTA Stiftung", "tensor-programming <tensordeveloper@gmail.com>" ]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://iota.org"

[dependencies]
paste = "1.0.1"
once_cell = "1.4"
serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false