[package]
name = "random"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]

[dependencies.primitives]
path = "../primitives"

[build-dependencies]
cc = "1.0"

